<style type="text/css">

<!--

.servicos {  
	font-family: Verdana, Arial, Helvetica, sans-serif; 
	font-size: 10px; 
	font-weight: bold; 
	color: #000000; 
	background-color: #E1ECFF; 
}

.caixa {  
	font-family: Verdana, Arial, Helvetica, sans-serif; 
	font-size: 10px; 
	font-weight: normal; 
	color: #000000; 
	background-color: #FFFFFF; 
}

.sair {  
	font-family: Verdana, Arial, Helvetica, sans-serif; 
	font-size: 10px; 
	font-weight: bold; 
	color: #000000; 
	background-color: #E1ECFF; 
}



.navegue {  
	font-family: Verdana, Arial, Helvetica, sans-serif; 
	font-size: 10px; 
	font-weight: bold; 
	color: #000000; 
	height: 19px; 
	width: 221px;
}

.texto {  
	font-family: Verdana, Arial, Helvetica, sans-serif; 
	font-size: 11px; 
	color: #000000; 
    font-weight: normal;
    text-decoration: none; 
}

.textorag {  
	font-family: Verdana, Arial, Helvetica, sans-serif; 
	font-size: 11px; 
	color: #000000; 
	text-align: left;
}

.textorodape { 
	font-family: Verdana, Arial, Helvetica, sans-serif; 
	font-size: 10px; 
	color: #000000 ; 
	font-weight: bold;
}

a:hover
{ text-decoration : underline;}

a:visited
{   color=#3333cc;}

a:link
{   color=#3333cc;}

a
{text-decoration : none; color=#3333cc;}

.subtitulo { 
	font-family: Verdana, Arial, Helvetica, sans-serif; 
	font-size: 14px; 
 	color: #00003;3
}

.input { 
	font-family: Verdana, Arial, Helvetica, sans-serif; 
	font-size: 11px; 
	color: #000000 ; 
	background-color: #eeeeee;
}

.textopeq {  
	font-family: Verdana, Arial, Helvetica, sans-serif; 
	font-size: 9px; 
	color: #000000;
}

BODY {
     font-family: verdana, lucida, arial, helvetica;
     font-size: 11px;
     COLOR: #000000;
     text-decoration: none; 
}

.textoBold {
	font-family: verdana, lucida, arial, helvetica; 
	font-size: 11px;
	font-weight: bold;
    text-decoration: none; 
    color: #000000;
}

.bgCinza {
        background: #e9e9e9;
        font-family: verdana, lucida, arial, helvetica;
        font-size: 11px;
        font-weight: bold;
        text-decoration: none; 
        color: #000066;
}	     

.bgAzul {
        background: #aaccff;
        font-family: verdana, lucida, arial, helvetica;
        font-size: 11px;
        font-weight: bold;
        text-decoration: none; 
        color: #000066;
}	     

TD {
	COLOR: #000000; 
        FONT-FAMILY: verdana, lucida, arial, helvetica; 
        FONT-SIZE: 11px; 
        FONT-WEIGHT: bold;
        text-decoration: none; 
}

P {
		COLOR: #000000; 
    	FONT-FAMILY: verdana, lucida, arial, helvetica; 
    	FONT-SIZE: 11px; 
        FONT-WEIGHT: bold;
        text-decoration: none; 
}

.verm {
	font-family: verdana, lucida, arial, helvetica; 
	font-size: 11px;
	font-weight: bold;
    text-decoration: none; 
    color: #aa0000;
}
-->
</style>

