<option value="3">Abu Dhabi	</option>
<option value="4">Afeganistão	</option>
<option value="5">Africa do Sul	</option>
<option value="6">Ajman	</option>
<option value="7">Albânia	</option>
<option value="8">Alemanha	</option>
<option value="9">Andorra	</option>
<option value="10">Angola	</option>
<option value="11">Antigua-Barbuda	</option>
<option value="12">Antilhas Holandesas	</option>
<option value="13">Arabia Saudita	</option>
<option value="14">Argélia	</option>
<option value="15">Argentina	</option>
<option value="16">Armênia	</option>
<option value="17">Aruba	</option>
<option value="18">Australia	</option>
<option value="19">Austria	</option>
<option value="20">Azerbaijão	</option>
<option value="21">Bahamas	</option>
<option value="22">Bangladesh	</option>
<option value="23">Barbados	</option>
<option value="24">Barein	</option>
<option value="25">Belgica	</option>
<option value="26">Belize	</option>
<option value="27">Benin	</option>
<option value="28">Bermuda	</option>
<option value="29">Bielorrússia	</option>
<option value="30">Birmânia	</option>
<option value="31">Bolivia	</option>
<option value="32">Bonaire	</option>
<option value="33">Bósnia Herzegovina	</option>
<option value="34">Botsuana	</option>
<option value="35">Brasil	</option>
<option value="36">Brunei	</option>
<option value="37">Bulgária	</option>
<option value="38">Burkina	</option>
<option value="39">Burundi	</option>
<option value="40">Butão	</option>
<option value="41">Cabo Verde	</option>
<option value="42">Camarões	</option>
<option value="43">Camboja	</option>
<option value="44">Canada	</option>
<option value="45">Casaquistão	</option>
<option value="46">Chile	</option>
<option value="47">China	</option>
<option value="48">Chipre	</option>
<option value="49">Colombia	</option>
<option value="50">Comores	</option>
<option value="51">Congo	</option>
<option value="52">Coréia do Norte	</option>
<option value="53">Coréia do Sul	</option>
<option value="54">Costa do Marfim	</option>
<option value="55">Costa Rica	</option>
<option value="56">Croacia	</option>
<option value="57">Cuba	</option>
<option value="58">Curaçao	</option>
<option value="59">Dinamarca	</option>
<option value="60">Djibouti	</option>
<option value="61">Dominica	</option>
<option value="62">Dubai	</option>
<option value="63">Egito	</option>
<option value="64">El Salvador	</option>
<option value="65">Emirados Árabes	</option>
<option value="66">Equador	</option>
<option value="67">Eritréia	</option>
<option value="68">Eslováquia	</option>
<option value="69">Eslovênia	</option>
<option value="70">Espanha	</option>
<option value="71">Estados Unidos	</option>
<option value="72">Estônia	</option>
<option value="73">Etiópia	</option>
<option value="74">Fiji	</option>
<option value="75">Filipinas	</option>
<option value="76">Finlândia	</option>
<option value="77">França	</option>
<option value="78">Fujairah	</option>
<option value="79">Gabão	</option>
<option value="80">Gâmbia	</option>
<option value="81">Gana	</option>
<option value="82">Geórgia	</option>
<option value="83">Gibraltar	</option>
<option value="84">Granada	</option>
<option value="85">Grecia	</option>
<option value="86">Guatemala	</option>
<option value="87">Guiana	</option>
<option value="88">Guiana Francesa	</option>
<option value="89">Guiné	</option>
<option value="90">Guiné Equatorial	</option>
<option value="91">Guiné-Bissau	</option>
<option value="92">Haiti	</option>
<option value="93">Holanda	</option>
<option value="94">Honduras	</option>
<option value="95">Hong Kong	</option>
<option value="96">Hungria	</option>
<option value="97">Iêmen	</option>
<option value="98">Ilhas Cook	</option>
<option value="99">Ilhas Marchal 	</option>
<option value="100">Ilhas Salomão	</option>
<option value="101">Ilhas Turks E Caicos	</option>
<option value="102">Ilhas Virgens Britânicas	</option>
<option value="103">India	</option>
<option value="104">Indonesia	</option>
<option value="105">Inglaterra	</option>
<option value="106">Irã	</option>
<option value="107">Iraque	</option>
<option value="108">Irlanda	</option>
<option value="109">Islândia	</option>
<option value="110">Israel	</option>
<option value="111">Italia	</option>
<option value="112">Servia	</option>
<option value="113">Jamaica	</option>
<option value="114">Japao	</option>
<option value="115">Jordania	</option>
<option value="116">Kiribati	</option>
<option value="117">Kuwait	</option>
<option value="118">Laos	</option>
<option value="119">Lesoto	</option>
<option value="120">Letonia	</option>
<option value="121">Libano	</option>
<option value="122">Libéria	</option>
<option value="123">Líbia	</option>
<option value="124">Liechtenstein	</option>
<option value="125">Lituânia	</option>
<option value="126">Luxemburgo	</option>
<option value="127">Macau	</option>
<option value="128">Macedônia	</option>
<option value="129">Madagascar	</option>
<option value="130">Malásia	</option>
<option value="131">Malavi	</option>
<option value="132">Maldivas	</option>
<option value="133">Mali	</option>
<option value="134">Malta	</option>
<option value="135">Marrocos	</option>
<option value="136">Martinica	</option>
<option value="137">Maurício	</option>
<option value="138">Mauritânia	</option>
<option value="139">Mexico	</option>
<option value="140">Moçambique	</option>
<option value="141">Moldávia	</option>
<option value="142">Monaco	</option>
<option value="143">Mongólia	</option>
<option value="144">Namíbia	</option>
<option value="145">Nauru	</option>
<option value="146">Nepal	</option>
<option value="147">Nicarágua	</option>
<option value="148">Níger	</option>
<option value="149">Nigéria	</option>
<option value="150">Noruega	</option>
<option value="151">Nova Caledonia	</option>
<option value="152">Nova Zelandia	</option>
<option value="153">Omã	</option>
<option value="154">Panama	</option>
<option value="155">Papua Nova Guiné	</option>
<option value="156">Paquistão	</option>
<option value="157">Paraguai	</option>
<option value="158">Peru	</option>
<option value="159">Polonia	</option>
<option value="160">Porto Rico	</option>
<option value="161">Portugal	</option>
<option value="162">Possessao Americana Na Oceania</option>
<option value="163">Possessão Australiana</option>
<option value="164">Possessão Britânica Exterior A Gibraltar</option>
<option value="165">Possessao Britanica Na America</option>
<option value="166">Possessão Britânica Na Oceania</option>
<option value="167">Possessão Dinamarquesa</option>
<option value="168">Possessão Espanhola</option>
<option value="169">Possessão Portuguesa Na África</option>
<option value="170">Principado De Liechtenstein</option>
<option value="171">Qatar	</option>
<option value="172">Quenia	</option>
<option value="173">Quirguízia	</option>
<option value="174">R.F. Iugoslávia	</option>
<option value="175">Ras Al-Kaimar	</option>
<option value="176">República Centro Africana	</option>
<option value="177">Republica Dominicana	</option>
<option value="178">República Tcheca	</option>
<option value="179">Romênia	</option>
<option value="180">Ruanda	</option>
<option value="181">Rússia	</option>
<option value="182">Saint Kitts	</option>
<option value="183">Samoa	</option>
<option value="184">San Marino	</option>
<option value="185">Santa Lucia	</option>
<option value="186">São Tomé E Principe	</option>
<option value="187">São Vicente	</option>
<option value="188">Seichelles	</option>
<option value="189">Senegal	</option>
<option value="190">Serra Leoa	</option>
<option value="191">Sharjah	</option>
<option value="192">Cingapura	</option>
<option value="193">Síria	</option>
<option value="194">Somália	</option>
<option value="195">Sri Lanka	</option>
<option value="196">Sudão	</option>
<option value="197">Suecia	</option>
<option value="198">Suica	</option>
<option value="199">Suriname	</option>
<option value="200">Swaziland	</option>
<option value="201">Tailândia	</option>
<option value="202">Taiwan	</option>
<option value="203">Tajaquistão	</option>
<option value="204">Tanzania	</option>
<option value="205">Tchad	</option>
<option value="206">Territórios Autonomos</option>
<option value="207">Togo	</option>
<option value="208">Tonga	</option>
<option value="209">Trinidad e Tobago	</option>
<option value="210">Tunisia	</option>
<option value="211">Turcomenistão	</option>
<option value="212">Turquia	</option>
<option value="213">Tuvalu	</option>
<option value="214">Ucrânia	</option>
<option value="215">Uganda	</option>
<option value="216">Umm Al Quwain	</option>
<option value="217">Uruguai	</option>
<option value="218">Uzbequistão	</option>
<option value="219">Vanuatu	</option>
<option value="220">Vaticano	</option>
<option value="221">Venezuela	</option>
<option value="222">Vietnã	</option>
<option value="223">Zaire	</option>
<option value="224">Zambia	</option>
<option value="225">Zimbabue	</option>
<option value="227">Território Palestino</option>
